### ISSUE TITLE
RuntimeError: einsum(): subscript l has size 300 for operand 1 which does not broadcast with previously seen size 10

### ISSUE THREAD

**Issue by zmhsmart** [boycehbz/DMMR#20]
/home/pbc/miniconda3/envs/zxh/lib/python3.8/site-packages/torch/utils/_contextlib.py:125: UserWarning: Decorating classes is deprecated and will be disabled in future versions. You should only decorate functions or methods. To preserve the current behavior of class decoration, you can directly decorate the __init__ method and nothing else.
  warnings.warn("Decorating classes is deprecated and will be disabled in "
Processing: doubleB/Camera00/00001.jpg
load pretrain parameters from data/motionprior_hp.pkl
/home/pbc/miniconda3/envs/zxh/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/pbc/miniconda3/envs/zxh/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or None for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing weights=ResNet50_Weights.IMAGENET1K_V1. You can also use weights=ResNet50_Weights.DEFAULT to get the most up-to-date weights.
  warnings.warn(msg)
betas shape: torch.Size([1, 10])
shape_disps shape: torch.Size([6890, 3, 300])
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    main(**args)
  File "main.py", line 33, in main
    setting = load_camera(data, setting, **args)
  File "/home/pbc/project/inference/DMMR/DMMR-main/core/utils/module_utils.py", line 694, in load_camera
    extris = extris_est(spin, data, data_folder, intris)
  File "/home/pbc/project/inference/DMMR/DMMR-main/core/utils/module_utils.py", line 568, in extris_est
    output, vert = spin(norm_img)
  File "/home/pbc/miniconda3/envs/zxh/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/pbc/project/inference/DMMR/DMMR-main/core/SPIN/spin.py", line 33, in forward
    pred_output, verts = self.smpl(betas=pred_betas, body_pose=pred_rotmat[:,1:], global_orient=pred_rotmat[:,0].unsqueeze(1), pose2rot=False)
  File "/home/pbc/miniconda3/envs/zxh/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/pbc/project/inference/DMMR/DMMR-main/core/SPIN/smpl.py", line 19, in forward
    smpl_output = super(SMPL, self).forward(*args, **kwargs)
  File "/home/pbc/project/inference/DMMR/DMMR-main/core/smplx/body_models.py", line 373, in forward
    vertices, joints = lbs(betas, full_pose, self.v_template,
  File "/home/pbc/project/inference/DMMR/DMMR-main/core/smplx/lbs_.py", line 179, in lbs
    v_shaped = v_template + blend_shapes(betas, shapedirs)
  File "/home/pbc/project/inference/DMMR/DMMR-main/core/smplx/lbs_.py", line 268, in blend_shapes
    blend_shape = torch.einsum('bl,mkl->bmk', [betas, shape_disps])
  File "/home/pbc/miniconda3/envs/zxh/lib/python3.8/site-packages/torch/functional.py", line 373, in einsum
    return einsum(equation, *_operands)
  File "/home/pbc/miniconda3/envs/zxh/lib/python3.8/site-packages/torch/functional.py", line 378, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: einsum(): subscript l has size 300 for operand 1 which does not broadcast with previously seen size 10

![Uploading PixPin_2024-07-16_20-41-50.png…]()

I am glad to see this exciting project, but I got this error when running it. My smpl model name is correct, but the dimension is wrong. How should I solve it? Thank you?

**Comment by boycehbz** [comment]
Please confirm that your SMPL_NEUTRAL.pkl is downloaded from SMPLify website. Thank you!

**Comment by zmhsmart** [comment]
Thanks, I have successfully run the code!!!
